import Head from 'next/head'
import Footer from '../components/Footer/Footer';
import { Container } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/layout.scss'
import '../styles/card.scss'
import '../styles/about.scss'

import '../styles/globals.scss'
import MobileHeader from '../components/MobileHeader/MobileHeader';
import Header from '../components/Header/Header';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Шаблон сайта министерства</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={true}></link>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap" rel="stylesheet"></link>
      </Head>
      <Header
        compressedName='Минэкономиразвития РТ' 
        fullName='Министертсво экономического развития и промышленности Республики Тыва'/>
      <MobileHeader />
      <Container className='body-container'>
        <Component {...pageProps} />
      </Container>
      <Footer phone={'+7 999 124 5548'} email={'someemail@mail.ru'}/>
    </>
  )
}

import fsPromises from 'fs/promises';
import path from 'path'

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'data.json');
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);

  return {
    props: objectData
  }
}

export default MyApp
