import Head from 'next/head'
import Footer from '../components/footer'
import Header from '../components/header'
import MobileHeader from '../components/mobile-header'
import { Container } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/layout.scss'
import '../styles/card.scss'

import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Шаблон сайта министерства</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <MobileHeader/>
      <Container>
        <Component {...pageProps} />
      </Container>
      <Footer />
    </>
  )
}

export default MyApp
