import Head from 'next/head'
import Footer from '../components/Footer/Footer';
import { Container } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/layout.scss'
import '../styles/card.scss'
import '../styles/about.scss'

import '../styles/globals.scss'
import MobileHeader from '../components/MobileHeader/MobileHeader';
import Header from '../components/Header/Header';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Шаблон сайта министерства</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap" rel="stylesheet"></link>
      </Head>
      <Header/>
      <MobileHeader/>
      <Container className='body-container'>
        <Component {...pageProps} />
      </Container>
      <Footer />
    </>
  )
}

export default MyApp
