import Header from "../components/header";
import Head from 'next/head'
import MobileHeader from "../components/mobile-header";

export default function About(){
  return(
    <>
      <Head>
        <title>О министерстве</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <MobileHeader />
      О министерстве
    </>
  )
}