import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import News from './news'
import styles from '../styles/home.module.css'
import MobileHeader from '../components/mobile-header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MobileHeader />
      <div className={styles.container}>

        {/* <News/> */}
      </div>
    </>

  )
}
