import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import News from './news'
import styles from '../styles/Home.module.css'
import MobileHeader from '../components/mobile-header'
import Service from '../components/govservice'
import Resourse from '../components/govresourses'
import Footer from '../components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Шаблон сайта министерства</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <MobileHeader />
      <div className={styles.container}>

        {/* <News /> */}
        
        <Service />

        <Resourse/>
      </div>

      <Footer/>
    </>

  )
}
